# Generated by Django 4.1.3 on 2025-01-14 16:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('simplybooksapi', '0003_bookgenre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookgenre',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='genrebooks', to='simplybooksapi.book'),
        ),
        migrations.AlterField(
            model_name='bookgenre',
            name='genre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookgenres', to='simplybooksapi.genre'),
        ),
    ]
